name: Nix Flake Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  nix-flake-update:
    name: "Nix Flake Update"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          token: ${{ steps.generate-token.outputs.token }}
