name: Nix Flake Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  nix-flake-update:
    name: "Nix Flake Update"
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required by actions/checkout.
      id-token: write # Required by Determinate Nix.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11 # v3.22.2
      - run: nix flake update
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - name: Create a pull request
        run: |-
          create_or_update_pr() {
            local branch="$1"
            local title="$2"
            local body="${3:-}"
            local base="${4:-master}"
            local pr_num
            pr_num=$(gh pr list --head "$branch" --json number -q '.[0].number // empty')
            if [ -z "$pr_num" ]; then
              gh pr create --title "$title" --body "$body" --base "$base" --head "$branch"
            else
              gh pr edit "$pr_num" --title "$title"
            fi
          }
          git config --local user.name "${APP_SLUG}[bot]"
          git config --local user.email "${APP_SLUG}[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git checkout -B nix-flake-auto-update
            git commit -am "Update Nix flake inputs"
            gh auth setup-git
            git push --force origin nix-flake-auto-update
            create_or_update_pr \
              nix-flake-auto-update \
              "Update Nix flake inputs" \
              "Updates all Nix flake inputs to the latest version."
          fi
        env:
          APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
