name: Nix Flake Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  nix-flake-update:
    name: "Nix Flake Update"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
